version: "3.1"
services:
  tomcat:
    image: tomcat:8.0
    ports:
      - 8080:8080
      - 4000:4000

    environment:
      JAVA_OPTS: -javaagent:/glowroot/glowroot.jar

    volumes:
      - ./glowroot:/glowroot
